// auto generated by ./scripts/types.js

declare type MessageParameters = {
  "PLUS_MORE": {
    num: number,
  },
  "REPLYING_TO_USER": {
    user: string,
  },
  "SENT_A_STICKER": {
    name: string,
  },
  "STARBOARD_MESSAGE_IMAGE_N": {
    number: number,
  },
  "STARBOARD_MESSAGE_VIDEO_N": {
    number: number,
  },
  "STARBOARD_MESSAGE_FILE_N": {
    number: number,
  },
  "STARBOARD_MESSAGE_SPOILER": {
    content: string,
  },
  "OVERRIDE_NOT_FOUND": {
    name: string,
  },
  "SUCCESS_CREATE_OVERRIDE": {
    name: string,
    type: "channel" | "channelType" | "emoji" | "role",
    channels: number,
    emojis: number,
    roles: number,
  },
  "SUCCESS_CREATE_OVERRIDE_CHANNELS_NOTICE": {
    channels: number,
  },
  "SUCCESS_CREATE_EMOJI_OVERRIDE_NOTICE": {
    emojis: string,
  },
  "CONFIRMATION_DELETE_OVERRIDE": {
    name: string,
  },
  "SUCCESS_DELETE_OVERRIDE": {
    name: string,
  },
  "CONFIRMATION_RESET_OVERRIDE": {
    name: string,
  },
  "SUCCESS_RESET_OVERRIDE": {
    name: string | null,
  },
  "INHERITS_SETTINGS_FROM": {
    name: string,
  },
  "OVERRIDE_APPLY_CHANNELS": {
    other: number,
    channels: string,
  },
  "OVERRIDE_APPLY_CHANNEL_TYPES": {
    type: string,
  },
  "OVERRIDE_APPLY_ROLES": {
    other: number,
    channels: string | null,
    roles: string,
  },
  "OVERRIDE_APPLY_EMOJIS": {
    emojis: string,
    channels: string | null,
  },
  "NUMBER_STARS": {
    stars: number,
  },
  "NUMBER_CHARACTERS": {
    chars: number,
  },
  "SUCCESS_CHANGE_SETTINGS": {
    name: string,
  },
  "SUCCESS_CHANGE_SETTINGS_NOTICE": {
    notices: string,
  },
  "MISSING_ATTACH_FILES_PERMISSION_NOTICE": {
    channel: string,
  },
  "REQUIRED_STARS_CLASH_SET": {
    requiredStars: number,
    requiredToRemove: number,
  },
  "UNUSABLE_REACTION_EMOJIS_PROVIDED": {
    emojis: string,
  },
  "SETTING_ONLY_FOR_SERVER_SETTINGS": {
    setting: string,
  },
  "CANNOT_SEND_MESSAGES_IN_CHANNEL": {
    channel: string,
  },
  "CANNOT_SEND_EMBEDS_IN_CHANNEL": {
    channel: string,
  },
  "CANNOT_VIEW_CHANNEL": {
    channel: string,
  },
  "CANNOT_VIEW_VOICE_CHANNEL": {
    channel: string,
  },
  "CANNOT_READ_HISTORY_IN_CHANNEL": {
    channel: string,
  },
  "SUCCESS_EDIT_OVERRIDE": {
    name: string,
    changes: string,
  },
  "OVERRIDE_NOW_NAMED": {
    name: string,
  },
  "OVERRIDE_PRIORITY_NOW": {
    priority: string,
  },
  "OVERRIDE_NOW_INHERITS": {
    name: string,
  },
  "ALREADY_BLACKLISTED": {
    name: string,
  },
  "SUCCESSFULLY_BLACKLISTED": {
    name: string,
  },
  "SUCCESSFULLY_BLACKLISTED_USER_OR_ROLE": {
    type: "users" | "roles",
    filterBlacklistedUsers: boolean,
  },
  "NOT_BLACKLISTED": {
    name: string,
  },
  "SUCCESSFULLY_UNBLACKLISTED": {
    name: string,
  },
  "SUCCESSFULLY_CLEAR_BLACKLIST_ALL": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_BLACKLIST_USERS": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_BLACKLIST_ROLES": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_BLACKLIST_CHANNELS": {
    size: number,
  },
  "ALREADY_WHITELISTED": {
    name: string,
  },
  "SUCCESSFULLY_WHITELISTED": {
    name: string,
  },
  "NOT_WHITELISTED": {
    name: string,
  },
  "SUCCESSFULLY_UNWHITELISTED": {
    name: string,
  },
  "SUCCESSFULLY_CLEAR_WHITELIST_ALL": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_WHITELIST_USERS": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_WHITELIST_ROLES": {
    size: number,
  },
  "SUCCESSFULLY_CLEAR_WHITELIST_CHANNELS": {
    size: number,
  },
  "BLACKLIST_DESCRIPTION_ADD_ITEMS": {
    commands: string,
  },
  "NUMBER_OF_BLACKLISTED_ITEMS": {
    num: number,
  },
  "INHERITS_BLACKLISTED_ITEMS_FROM": {
    name: string,
  },
  "WHITELIST_DESCRIPTION_ADD_ITEMS": {
    commands: string,
  },
  "NUMBER_OF_WHITELISTED_ITEMS": {
    num: number,
  },
  "DISPLAY_TIER_FROM": {
    style: string,
    threshold: number,
  },
  "SUCCESSFULLY_CREATED_DISPLAY_TIER": {
    tier: string,
  },
  "DISPLAY_TIERS_DESCRIPTION_CREATE_TIER": {
    command: string,
  },
  "DISPLAY_TIER_NOT_BELONG": {
    command: string,
  },
  "DISPLAY_TIER_NOT_FOUND": {
    number: number,
    command: string,
  },
  "SUCCESSFULLY_DELETED_DISPLAY_TIER": {
    tier: string,
  },
  "SUCCESSFULLY_EDITED_DISPLAY_TIER": {
    old: string,
    tier: string,
  },
}

export = MessageParameters